name: Validate PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: yarn install --frozen-lockfile --silent
      - run: yarn lint
      - run: yarn build
      - run: yarn test:cov --ci
      - run: yarn test:e2e --ci
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONAR_TOKEN }}
        with:
          args: -Dsonar.projectKey=Evanion_nestjs-correlation-id
            -Dsonar.organization=evanion
